image: ruby:2.4.2

stages:
  - build
  - push
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  LATEST_VER: amolodchenko/redditapp:latest

before_script:
  - cd reddit

build_job:
  stage: build
  image: docker:stable

  script:
    - docker info
    - docker build -t $LATEST_VER .

push_job:
  stage: push
  image: docker:stable

  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER && docker image rm $LATEST_VER

test_unit_job:
  stage: test
  before_script:
    - bundle install
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  before_script:
    - bundle install
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  before_script:
    - bundle install
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
   name: branch/$CI_COMMIT_REF_NAME
   url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  before_script:
    - bundle install
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com
production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  before_script:
    - bundle install
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
