---
# tasks file for cfssl
- name: Download cfssl binary
  get_url:
    url: "https://pkg.cfssl.org/R1.2/cfssl_darwin-amd64"
    dest: "/usr/local/bin/cfssl"
    mode: 0755
    owner: "root"
    group: "root"
  tags:
    - cfssl

- name: Download cfssljson binary
  get_url:
    url: "https://pkg.cfssl.org/R1.2/cfssljson_darwin-amd64"
    dest: "/usr/local/bin/cfssljson"
    owner: "root"
    group: "root"
    mode: 0755
  tags:
    - cfssl
