global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksey_molodchenko'
