global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksey_molodchenko'
- name: 'email'
  email_configs:
    - to: 'support@ompany.com'
      send_resolved: true
      from: 'prometheus@company.com'
      smarthost: 'smtp.gmail.com:465'
      auth_username: 'prometheus@company.com'
      auth_password: 'Super$EcretP@$$w0rd'
