---
- name: Install Reddit Application
  hosts: all
  become: true
  tasks:
  - name: Run Reddit Application Container
    docker_container:
      name: reddit
      image: amolodchenko/otus-reddit:1.0
      ports:
        - "9292:9292"
    tags: app
