version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_SERVICE_VERSION}
    volumes:
      - post_db:${POST_SERVICE_VOLUME_PATH}
    networks:
      back_net:
       aliases:
       - post_db
       - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - ${UI_SERVICE_PORT}:${UI_SERVICE_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    networks:
      back_net:
       aliases:
       - comment
      front_net:
       aliases:
       - comment
  comment:
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
      back_net:
       aliases:
       - post
      front_net:
       aliases:
       - post
  prometheus:
    image: ${USERNAME}/prometheus
    networks:
      back_net:
       aliases:
       - prometheus
      front_net:
       aliases:
       - prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    user: root
    networks:
      back_net:
       aliases:
       - node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  mongodb-exporter:
    image: ${USERNAME}/mongodb_exporter:${MONGODB_EXPORTER_VERSION}
    command:
      - --collect.database
      - --collect.collection
      - --mongodb.uri=[mongodb://post_db:27017]
    # environment:
    #   - MONGODB_URL=mongodb://post_db
    ports:
      - 9216:9216
    networks:
      back_net:
       aliases:
       - mongodb_exporter
volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
