---
version: '3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd:${ELASTIC_VERSION}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back_net:
       aliases:
       - fluentd
      front_net:
       aliases:
       - fluentd
  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      back_net:
       aliases:
       - elasticsearch

  kibana:
    image: kibana:${KIBANA_VERSION}
    ports:
      - "5601:5601"
    networks:
      back_net:
       aliases:
       - kibana

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      back_net:
       aliases:
       - zipkin
      front_net:
       aliases:
       - zipkin

volumes:
  esdata1:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
