version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_SERVICE_VERSION}
    volumes:
      - post_db:${POST_SERVICE_VOLUME_PATH}
    networks:
      back_net:
       aliases:
       - post_db
       - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - ${UI_SERVICE_PORT}:${UI_SERVICE_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_SERVICE_VERSION}
    networks:
      back_net:
       aliases:
       - comment
      front_net:
       aliases:
       - comment
  comment:
    image: ${USERNAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
      back_net:
       aliases:
       - post
      front_net:
       aliases:
       - post
  prometheus:
    image: ${USERNAME}/prometheus
    networks:
      back_net:
       aliases:
       - prometheus
      front_net:
       aliases:
       - prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
