---
version: '3.3'
services:
  ui:
   entrypoint:
    - puma
    - --debug
    - -w 2
   volumes:
    - /home/${APP_USER_NAME}/ui:/app
  comment:
   entrypoint:
    - puma
    - --debug
    - -w 2
   volumes:
    - /home/${APP_USER_NAME}/comment:/app
  post:
   volumes:
    - /home/${APP_USER_NAME}/post-py:/app
