---
version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_SERVICE_VERSION}
    volumes:
      - post_db:${POST_SERVICE_VOLUME_PATH}
    networks:
      back_net:
       aliases:
       - post_db
       - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_SERVICE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_SERVICE_PORT}:${UI_SERVICE_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ${USER_NAME}/post:${POST_SERVICE_VERSION}
    depends_on:
      - post_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      back_net:
       aliases:
       - comment
      front_net:
       aliases:
       - comment
  comment:
    image: ${USER_NAME}/comment:${COMMENT_SERVICE_VERSION}
    depends_on:
      - post_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comments
    networks:
      back_net:
       aliases:
       - post
      front_net:
       aliases:
       - post
volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
