---
services:
  prometheus:
    image: ${USER_NAME}/prometheus
    networks:
      back_net:
       aliases:
       - prometheus
      front_net:
       aliases:
       - prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    user: root
    networks:
      back_net:
       aliases:
       - node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  mongodb-exporter:
    image: ${USER_NAME}/mongodb_exporter:${MONGODB_EXPORTER_VERSION}
    command:
      - --collect.database
      - --collect.collection
      - --mongodb.uri=[mongodb://post_db:27017]
    ports:
      - 9216:9216
    networks:
      back_net:
       aliases:
       - mongodb_exporter
  blackbox-exporter:
    image: ${USER_NAME}/blackbox_exporter:${BLACKBOX_EXPORTER_VERSION}
    ports:
      - 9115:9115
    networks:
      back_net:
       aliases:
       - blackbox_exporter
      front_net:
       aliases:
       - blackbox_exporter
  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000

volumes:
  prometheus_data:
  grafana_data:
