---
groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    - alert: HightResponceTime95
      expr: histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le)) >= 1
      for: 1m
      labels:
        severity: critical
      annotations:
        description: 'UI Service: 95 percentile of responce time is 1 second!'
        summary: '95 percentile of responce time is 1 second'
