
---
- name: Download && install kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/darwin/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    owner: "root"
    group: "root"
    mode: 0755
  tags:
    - kubectl
